
esphome:
  name: ${node_name}
  #name_add_mac_suffix: true

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: 2.0.6

i2c:
   - id: bus_a
     sda: 13
     scl: 14
     scan: true
     frequency: 100kHz
   - id: bus_b
     sda: 5
     scl: 4
     scan: true
     frequency: 100kHz

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO15

  

