substitutions:
  node_name: sid-on-black

packages:
# devices
  core: !include sid-on-black/devices/wt32_eth01.yaml
  internals: !include sid-on-black/devices/boneio_board.yaml
  #internals: !include sid-on-black/devices/boneio_board_MCP.yaml
  temp: !include sid-on-black/devices/lm75b.yaml
  display: !include sid-on-black/devices/display.yaml
  # uart: !include sid-on-black/devices/uart.yaml
  # one_wire: !include boneio_v0.5/devices/one_wire.yaml
# relay32
  #output: !include sid-on-black/boards/relay32_outputs_MCP.yaml
  output: !include sid-on-black/boards/relay24_outputs_MCP.yaml
  #output: !include sid-on-black/boards/relay32_outputs_PCF.yaml
  #input: !include sid-on-black/boards/relay32_inputs_MCP.yaml
  #input: !include sid-on-black/boards/relay32_inputs.yaml
  input: !include sid-on-black/boards/relay24_inputs.yaml
# dimmer led
  #output: !include sid-on-black/boards/dimmer_led8x4_outputs.yaml
  #input: !include sid-on-black/boards/dimmer_led8x4_inputs.yaml
  #light: !include sid-on-black/boards/monochromatic_lights.yaml
# cover
  #output: !include sid-on-black/boards/cover16_outputs.yaml
  #input: !include sid-on-black/boards/cover16_inputs.yaml
  #cover: !include sid-on-black/boards/cover.yaml

logger:
  baud_rate: 0
api:
ota:
  password: boneio
# disable web server - for testing only
web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time: