#i2c  address: 0x26 input pcf io
#i2c  address: 0x27 input pcf io
#i2c  address: 0x40 input ina219 power
#i2c  address: 0x68 input rtc ds1307
time:
  - platform: ds1307
    id: ds1307_time
    address: 0x68
    i2c_id: bus_b

sensor:
# Module power consmption
  - platform: ina219
    address: 0x40
    i2c_id: bus_b
    shunt_resistance: 0.1 ohm
    current:
      id: ina_current
      name: "${node_name} INA219 Current"
    power:
      id: ina_power
      name: "${node_name} INA219 Power"
    bus_voltage:
      id: ina_bus_voltage
      name: "${node_name} INA219 Bus Voltage"
    shunt_voltage:
      id: ina_shunt_voltage
      name: "${node_name} INA219 Shunt Voltage"
    max_voltage: 32.0V
    max_current: 3.2A
    update_interval: 30s

ads1115:
    i2c_id: bus_a
    address: 0x48

pcf8574:
  - id: 'pcf_input_1'
    i2c_id: bus_a
    address: 0x20
    pcf8575: true
  - id: 'pcf_input_2'
    i2c_id: bus_a
    address: 0x21
    pcf8575: true 
  - id: 'pcf_input_3'
    i2c_id: bus_a
    address: 0x22
    pcf8575: true

