light:
  - platform: monochromatic
    output: pca_output_1
    name: "${node_name} LED 01"
    id: led_1
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_2
    name: "${node_name} LED 02"
    id: led_2
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_3
    name: "${node_name} LED 03"
    id: led_3
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_4
    name: "${node_name} LED 04"
    id: led_4
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_5
    name: "${node_name} LED 05"
    id: led_5
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_6
    name: "${node_name} LED 06"
    id: led_6
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_7
    name: "${node_name} LED 07"
    id: led_7
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_8
    name: "${node_name} LED 08"
    id: led_8
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_9
    name: "${node_name} LED 09"
    id: led_9
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_10
    name: "${node_name} LED 10"
    id: led_10
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_11
    name: "${node_name} LED 11"
    id: led_11
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_12
    name: "${node_name} LED 12"
    id: led_12
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_13
    name: "${node_name} LED 13"
    id: led_13
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_14
    name: "${node_name} LED 14"
    id: led_14
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_15
    name: "${node_name} LED 15"
    id: led_15
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_16
    name: "${node_name} LED 16"
    id: led_16
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_17
    name: "${node_name} LED 17"
    id: led_17
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_18
    name: "${node_name} LED 18"
    id: led_18
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_19
    name: "${node_name} LED 19"
    id: led_19
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_20
    name: "${node_name} LED 20"
    id: led_20
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_21
    name: "${node_name} LED 21"
    id: led_21
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_22
    name: "${node_name} LED 22"
    id: led_22
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_23
    name: "${node_name} LED 23"
    id: led_23
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_24
    name: "${node_name} LED 24"
    id: led_24
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_25
    name: "${node_name} LED 25"
    id: led_25
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_26
    name: "${node_name} LED 26"
    id: led_26
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_27
    name: "${node_name} LED 27"
    id: led_27
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_28
    name: "${node_name} LED 28"
    id: led_28
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_29
    name: "${node_name} LED 29"
    id: led_29
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_30
    name: "${node_name} LED 30"
    id: led_30
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_31
    name: "${node_name} LED 31"
    id: led_31
    default_transition_length: 2s
  - platform: monochromatic
    output: pca_output_32
    name: "${node_name} LED 32"
    id: led_32
    default_transition_length: 2s
