
mcp23017:
  - id: 'mcp_outputs_1to16'
    address: 0x21
    i2c_id: bus_b
  - id: 'mcp_outputs_17to32'
    address: 0x20
    i2c_id: bus_b

switch:
  - platform: gpio
    id: relay_1
    name: "${node_name} Relay 01"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 0
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_2
    name: "${node_name} Relay 02"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 1
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_3
    name: "${node_name} Relay 03"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 2
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_4
    name: "${node_name} Relay 04"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 3
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_5
    name: "${node_name} Relay 05"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 4
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_6
    name: "${node_name} Relay 06"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 5
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_7
    name: "${node_name} Relay 07"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 6
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_8
    name: "${node_name} Relay 08"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 7
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_9
    name: "${node_name} Relay 09"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 0
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_10
    name: "${node_name} Relay 10"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 1
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_11
    name: "${node_name} Relay 11"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 2
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_12
    name: "${node_name} Relay 12"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 3
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_13
    name: "${node_name} Relay 13"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 4
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_14
    name: "${node_name} Relay 14"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 5
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_15
    name: "${node_name} Relay 15"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 6
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_16
    name: "${node_name} Relay 16"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 7
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_17
    name: "${node_name} Relay 17"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 15
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_18
    name: "${node_name} Relay 18"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 14
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_19
    name: "${node_name} Relay 19"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 13
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_20
    name: "${node_name} Relay 20"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 12
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_21
    name: "${node_name} Relay 21"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 11
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_22
    name: "${node_name} Relay 22"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 10
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_23
    name: "${node_name} Relay 23"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 9
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_24
    name: "${node_name} Relay 24"
    pin:
      mcp23xxx: mcp_outputs_1to16
      number: 8
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_25
    name: "${node_name} Relay 25"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 15
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_26
    name: "${node_name} Relay 26"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 14
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_27
    name: "${node_name} Relay 27"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 13
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_28
    name: "${node_name} Relay 28"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 12
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_29
    name: "${node_name} Relay 29"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 11
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_30
    name: "${node_name} Relay 30"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 10
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_31
    name: "${node_name} Relay 31"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 9
      mode:
        output: true
      inverted: false

  - platform: gpio
    id: relay_32
    name: "${node_name} Relay 32"
    pin:
      mcp23xxx: mcp_outputs_17to32
      number: 8
      mode:
        output: true
      inverted: false
